# multus-test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: multus-test
  annotations:
    k8s.v1.cni.cncf.io/networks: logging-net
spec:
  containers:
  - name: test
    image: alpine
    command: ["sleep", "3600"]