:source-highlighter: highlightjs
:highlightjs-theme: github-dark
:title: Ten Minute Training

== Ten Minute Training

https://www.youtube.com/playlist?list=PLLWMQd6PeGY1MtyfNc0RbJSrC9LRUmT-6[youtube playlist]

=== Constant Interpolation in C# 10 and .NET 6 In 10 Minutes or Less
.String interpolation in constant time situations
[%collapsible]
====
new constant evaluation of strings in C# 6.0, we can use string interpolation. better to `const` then `readonly`.

[source, csharp]
----
const string companyName = "Acme"; // no problem
const string productName = $"{companyName} Anvils";  // new for C# 10
const string productDescription = $"{productName} are the best way to crush your enemies";
----

one place where we can use this is for attributes,allowing them to have custom text.
[source, csharp]
----
[Obsolete($"This is no longer used for {companyName}")]
void SayHi()
{

}
----
====

=== Date and Time in C# 10 and .NET 6 In 10 Minutes or Less
.Simplified Objects for Data and Time
[%collapsible]
====
until C# 10, we had a combined object for Date and Time. now we can have separate objects, which we can work on in different ways. such as taking the month and the day of the week for date only objects, and it will also not have weird rollOver behavior depending on timezones. it's not a full dateTime object. +
the timeOnly object is also just for time, without caring about timezones and other stuff.


[source, CSharp]
----
var  dateTime = DateTime.Now;
Console.WriteLine(dateTime);
DateOnly dateOnly = DateOnly.FromDateTime(DateTime.Now);
TimeOnly timeOnly = TimeOnly.FromDateTime(DateTime.Now);
----

====

=== Deconstructor Updates in C# 10 and .NET 6 In 10 Minutes or Less
.Mix and Match tuple unpacking
[%collapsible]
====

we start with tuple, we can do tuple de-construction and unpack it, we can also declare the variable ahead of time and unpack it, but until C#10, we couldn't combine them.
[source, CSharp]
----
var person = (FirstName: "Time", LastName: "Corey");
(string fName, string lName) = person; // inline declaration worked in c#9

string fn;
string ln;

(fn,ln) = person; // declared ahead of time
(fn, string lastName) = person; // mix and match styles

----

====

=== File Scoped Namespaces in C# 10 and .NET 6 In 10 Minutes or Less

.A Different way of marking the namespace
[%collapsible]
====

file scoped namespace, in the past, we had all of our code inside a namespace, in a block scope manner, so everything was indented inside the file.

[source, csharp]
----
namespace OldWay
{
  public class oldClass
  {

  }
}
----

the new way allows us to declare namespaces just for the file, which allows us to start writing code from the left most side of the file.

NOTE: we can only have one namespace per file this way, which is how it should be anyway

[source, csharp]
----
namespace newWay;
public class newWay
{

}
----
====

=== Global Usings in C# 10 and .NET 6 In 10 Minutes or Less

.Removing Boilerplate import statements
[%collapsible]
====

we can move all the `using` statements into a single file, and then it's implicitly used everywhere.

when we mark a using statement with `global using`, then it will available for all other files in the project. the bast way to do this is to combine the global statements into a single file.

this can also work with `global using static` to drop some boiler plate code.

CAUTION: there is a reason that we have namespace, we should make sure to avoid namespace pollution and confusion,
====

=== Null Parameter Checks in C# 10 and .NET 6 In 10 Minutes or Less

.Easy Null Check and throwing exceptions
[%collapsible]
====


if we want to protect against null values, we usually use check manually for null and throw `ArgumentNullException`. but now we can do it directly.
[source, csharp]
----
string? info = null;
void SayHi(string message)
{
  ArgumentNullException.ThrowIfNull(message); 
  Console.WriteLine($"Hello {message}");
}
----
====

=== Hot Reload in .NET 6 In 10 Minutes or Less

.Hot reload works anywhere
[%collapsible]
====
hot reloading means the application is updated as code changes but without restarting it. there is a "fire" icon in visual studio. the state of the program remains.

it should work on Blazor and also older c# projects, like WPF.

this makes the development loop much faster.

since this works with 'dot.net watch' (the command line version), then hot reload will also work with visual studio code.
====

=== Intro to Tuples in C# In 10 Minutes or Less

.Using Tuples as a return type
[%collapsible]
====

returning more than one value, we could use out parameters (like `out ref`) or create a specific class for it. but it's easier to return a tuple.

we can name the resulting parameters and the refer to it as the named elements (rather than item1 and item2) or unpack it directly. we can also use the discard character - the underscore `_` if we don't care about one of the values.

[source, csharp]
----

(string address, bool isValid) ValidateAddress(string address)
{
  return ("as", false);
}
----
====

=== Parameter and Variable Tooltips in Visual Studio In 10 Minutes or Less

.Visual Studio Editor Hints
[%collapsible]
====

in the settings menu, we can turn on "inline variable hints", which would display the names of the positional parameters. we can also display inline type hints when we use the `var` keyword. this is very good for LINQ expressions

[source, csharp]
----
(string message, int length) SayHello(string firstName, string lastName)
{
  string output = $"Hello {firstName} {lastName}";
  return (output, output.Length);
}
----
====

=== Implicit Usings in .NET 6 In 10 Minutes or Less
.Auto Generated `Using`s
[%collapsible]
====

we no longer need to write directly `using System;` to use the console. the most common import statements are auto generated into the "global usings" file.  it will have the `global using global::System;` statement and it will be directly available from all files. we can turn this feature off by modifying the the project file and disabling it. we can also add and remove them with "ItemGroup" attributes and even give them aliases in a global way.

[source, xml]
----
<ItemGroup>
  <Using Remove="System"/>
  <Using Include="System.Data"/>
  <Using Include="SomeProject.Data.SQL" Alias="SQLDA"/>
</ItemGroup>
----
====

=== Tweaking Kestrel

.Setting how launching web servers works
[%collapsible]
====
Kestrel and IIS are ways of creating local web servers. we can tweak the setting in the "launchSettings.json" file. we can change the profiles, the ports (http and https) and environment variables. 
====

=== Custom Naming Styles in Visual Studio 2022
.Customizing Naming styles and warning
[%collapsible%open]
====
We can change the Code style suggestion and auto generations of code. we can create new styles and assign severities for them.
====

=== The New MongoDB Analyzer In 10 Minutes or Less

.Analyzing MongoDB C# code
[%collapsible]
====
A Roselyn analyzer, so we need to install the package from nuget "MongoDb.analyzer". This helps us analyze C# code queries and show us the raw query, and it tells us if the query is recognized by mongoDB or if it's broken somehow.

if we want to change the settings, we need a file "mongodb.analyzer.json" at the root folder.
====

=== Getting a MongoDB Atlas Connection String In 10 Minutes or Less

.Connecting to Mongo AtlasDB
[%collapsible]
====
we go to the AtlasDB web console and grab the connection string for an application and take the C# version. we can also grab a code sample from there.

we need to replace the "<password>" and database as the default database. in visualStudio we add the string to the launch settings or at the user secrets file.

====

=== Editorconfig In Visual Studio In 10 Minutes or Less

.Per Project Configurations
[%collapsible]
====
Some settings shouldn't be global, but set for each project. such as editor preferences, code styles, etc... rather than have all developers set their IDE in the same way, we can push the changes into a editorConfig file and have them as part of the source control.
====

=== Intro to Core WCF In 10 Minutes or Less

.WCF is now compatible with .Net Core
[%collapsible]
====

CoreWCF is a way to bring existing WCF code into .Net Core and move away from .Net framework. WCF is Windows Communication Foundation, and should have been replaced with gRPC. the CoreWCF comes with new templates 
====

=== Intro to Core WCF In 10 Minutes or Less

.Features Worth knowing
[%collapsible]
====
An api project type

* authentication
* docker
* controllers
* openAPI Support (swagger)
** xml code comments
** web console
* built-in dependency injection
* the "appsettings.json"
** normal
** development phase overrides
** user only secrets
* default logger service
* data validation of models
** `[Required]`
** `[MinLength]`

====

=== NET 7 Update: Simplified LINQ Ordering In 10 Minutes or Less

.Simplified Ordering in LINQ statements
[%collapsible]
====

when there is a default ordering for objects (IComparable) then we can use the default ordering in LINQ.

[source, csharp]
----
var ages = new List<int>() {51, 87, 23, 84};
var sortedOld = ages.OrderBy(x => x);
var sortedNew = ages.Order();
----
there is also `OrderDescending()`.
====

=== .NET 7 Update: Nullable Models in MVC in 10 Minutes or Less

.Views can accept nullable models.
[%collapsible]
====
nullable page and view models in Blazor apps. MVC is model-view-controller. +
we can now have nullable views and handle this case.

[source, cshtml]
----
@model List<string>?

@{
  ViewData["Title"] = "ToDo";
}

<h1>ToDo</h1>

@if(Model is null)
{
  <p>You have no ToDo items</p>
}
else
{
  <ul>
  @foreach (var todo in Model)
  {
    <li>@todo</li>
  }
  </ul>
}
----
in the example code, we have a null list (not empty), so we can protect against null values

====

=== .NET 7 Update: Blank Templates for Blazor in 10 Minutes or Less

.Blank Templates For Blazor.
[%collapsible]
====

new templates for blazor Web Assembly in .Net 7, we can use an "full" template or an "empty" one, the full template had a starting application (weather forecast) with some example pages to work from, the empty template is cleaner and is trimmed down.

the full templates are great for starting and learning good practices, and the blank template is for more advanced users.
====

=== .NET 7 Update: Nanoseconds in DateTime in 10 Minutes or Less

.Access to MicroSeconds and NanoSeconds in Time Objects.
[%collapsible]
====

added direct access for micro and nano seconds properties of time objects such as DateTime, TimeStamp, DateTimeOffset and TimeOnly. + 
before .Net7 we had those values from calculating the ticks, the level of precision didn't increase, and we get nano seconds in precision of hundred nanoseconds (0,100,...,800,900). 

[source, csharp]
----
DateTime demo = DateTime.Now;
Console.WriteLine($"Ticks: {demo.Ticks}");
Console.WriteLine($"Micro Seconds: {demo.Microsecond}");
Console.WriteLine($"Nano Seconds: {demo.Nanosecond}");
----

====

=== .NET 7 Update: Creating Tar Files in C# in 10 Minutes or Less

.Support for Tar Archive Files Operations.
[%collapsible]
====

windows uses zip files, but unix machines use tar files for archive. wc can create and extract from the tar files.
[source, csharp]
----
using System.Formats.Tar;

TarFile.CreateFromDirectory(@"c:\temp\TarDemo\Source", @"c:\temp\TarDemo\Demo.tar", false); // string literal

TarFile.ExtractToDirectory(@"c:\temp\TarDemo\Demo.tar",@"c:\temp\TarDemo\Extracted", false); // not overwriting existing files
----
====

=== .NET 7 Update: Raw String Literals in 10 Minutes or Less

.Raw String Literals with Custom Starting Markers.
[%collapsible]
====
Raw string literals, csharp 11. verbatim strings have problem with indentations and how the date differs in the code and values. raw string literals use the three double quotes like python multi-line strings. if we want to use three consecutive quotes inside the text, we can simply decide to use four quotes as the start and end markers. if we wnt string interpolation, we can use the "$" sign, and if we have curly braces as part of the text, we can use "$$" in the starting string so only double curly braces will be interpolated.

[source, csharp]
----
string rawString;
rawString = @"C:\Test{hello}"; // verbatim 
rawString = @$"C:\Test{hello}"; // verbatim with string interpolation
rawString ="""
{
  "Json":{
    "Inner":"abc",
    "Other": 111,
    "Third":["a","b","c"]
  }
}
"""; // raw string literal

var level = "waring";
rawString =$$""""
{
  "Json":{
    "Inner":"""abc",
    "Level": "{{level}}",
    "Other": 111,
    "Third":["a","b","c"]
  }
}
""""; // raw string literal with interpolation
----

====

=== .NET 7 Update: Required Properties in 10 Minutes or Less

.Require New Objects to Initialize Property Members. 
[%collapsible]
====
ensuring properties have values, without requiring a constructor, otherwise we might get un intended null values. however, we need to mark our constructors and indicate the fullfil the requirements with `[SetsRequiredMembers]`.

old way
[source, csharp]
----
public class Person{
  public string FirstName {get; set;}
  public string LastName {get; set;}
  public Person(string first, string last)
  {
    FirstName = first;
    LastName = last
  }
  public Person()
  {
    FirstName = "first";
    LastName = "last"
  }
}
----

new way - marking properties as "required" so any creation must assign values to it
[source, csharp]
----
public class Person {
  public required string FirstName {get; set;}
  public required string LastName {get; set;}

  [SetsRequiredMembers]
  public Person(string first, string last)
  {
    FirstName = first;
    LastName = last
  }
}
----
====

=== .NET 7 Update: Blazor Loading Animation in 10 Minutes or Less

.Pre Configured Loading Animation in Blazor Apps.
[%collapsible]
====
Just for blazor web assembly, not for blazor web server.

There is circle graph that fills up in percentages to display loading progress in blazor apps.

we can modify the starting animation in the "index.html" file. this is exposed via a css variable.
====

=== .NET 7 Update: Blazor Virtualization Update in 10 Minutes or Less

.Virtualizing Table Elements in Blazor Apps
[%collapsible]
====
The suggestion site uses Blazor and has virtualization to render the suggestion list. objects are loaded and unloaded at runtime. in the "inspect"

but in some cases it can't do this virtualization simply. we can't add "div" elements to a table directly, so we add `<Virtualize>` and add "SpacerElement" to determine which type of element to virtualize.

[source, cshtml]
----
<tbody>
  <Virtualize Items="@forecasts" Context="forecast" OverScanCount="50" SpacerElement="tr">
    <tr>
      <td>@forecast.Data.ToShortDateString()</td>
      <td>@forecast.TemperatureC</td>
      <td>@forecast.TemperatureF</td>
      <td>@forecast.Summary</td>
    </tr>
  </Virtualize>
</tbody>
----
this makes the fetching faster and needs less memory.
====

=== .NET 7 Update: List Patterns in 10 Minutes or Less

.Pattern Matching on Lists And Arrays
[%collapsible]
====
[source, csharp]
----
csv = "some,text,data";
string[] info = csv.Split(',');

if (info is [var id, _, _)])
{
  Console.WriteLine($"Id is {id} and has exactly three values");
}
else {
  Console.WriteLine("bad input");
}
----
if we want to match zero or more matches, we can use `..` (two dots) to discard zero or more variables, and we can also capture afterwards, so we could take the first three and last three elements, and discard all the rest.

we can also validate directly on values.

[source, csharp]
----
csv = "1,sue,storm,dis,dis,final";
string[] info = csv.Split(',');

if (info is ["1" or "2", var firstName, var lastName), .., var last])
{
  Console.WriteLine($"Id is {id} and has exactly three values");
}
else {
  Console.WriteLine("bad input");
}
----
====

=== .NET 7 Update: Newlines in String Interpolation in 10 Minutes or Less

.We Can Break Our String Interpolation Code Into Different Lines.
[%collapsible]
====

[source, csharp]
----
int age = 44;
string ageText = age switch
{
  > 80 => "old",
  > 60 => "getting old"
  > 20 => "a good age"
  _    => "young"
};

Console.writeLine($"The user is {age} years old, which is {ageText}");
----
we can replace it with a single line and perform the switch case inside. now we can break through our string interpolation and make it more readable.

[source, csharp]
----
int age = 44;
Console.writeLine($"The user is {age} years old, which is {age switch
  {
    > 80 => "old",
    > 60 => "getting old"
    > 20 => "a good age"
    _    => "young"
  }
}".);
----
====

=== Running RabbitMQ Locally with Docker

.Running RabbitMQ Locally on a Docker Container
[%collapsible]
====
RabbitMQ is an open source message broker for publisher/subscriber pattern.

Using docker-desktop is the easiest way

[source, shell]
----
docker container run -d -h rmq --name rabbit-server -p 8080:15672 -p 5672:5672 rabbitMQ:3-management
----

* `-d, --detached` for detached, so it's not tied to the terminal which ran it.
* `-h, --hostname` the name of the hosting container.
* `--name` is the container name.
* `-p, --port` maps port from the hosting machine to the container.

we can navigate to rabbitMQ server in our browser with the default user name and password (both "guest").
====

=== Adding Blazor Components with Drag and Drop

.Drag and Drop Blazor Components.
[%collapsible]
====
all blazor pages are components, and instead of writing `<ComponentName />`, we can drag it from the solution explorer.

[source, csharp]
----
@code {
  [Parameter]
  [EditorRequired]
  public int StartingValue {get; set;}
  private int currentValue = 0;
  private void IncrementCount()
  {
    currentCode++;
  }
}
----
we can also annotate the component with the `[EditorRequired]`attribute and then it's also added by default when dragging and dropping, so it will show up `<ComponentName StartingValue="8" />`

====

=== Blazor Code Separation - Easily Moving Code to a Code Behind File

.Moving CSharp Component Code Into Separate Files.
[%collapsible]
====
Separating application code from html and blazor code. rather than having `@code` blocks in the components, we can move them to "*.razor.cs" files as the code-behind. we can right click the code block and visual studio creates a partial class. + 
Because it's a partial class, dependency injection using the blazor syntax still work, even if the injection doesn't show up in the code behind file.
====

=== Correct String Initialization in C#

.Different Options to Initialize a String.
[%collapsible]
====

when we create a string value, we can give it some non-value value.
[source, csharp]
----
string? test1 = null;
string? test2 = string.Empty;
string? test3 = "";
string? test4 = default;
----

the equivalent cases are `null` and `default` as one case, and `string.Empty` and `""` as the other case. +
Using the null value indicates the absence of a value, and the empty string is the "starting" value. sometimes it makes sense to not have a value, and sometimes its preferable to make sure there always a value there. +
There is one situation where we have to use `""` and not `string.Empty`, this is inside switch statement, which must have a value. and we can't use `string.Empty` as a default value for function parameters.
====

=== Shortcut for Wrapping Element in a Div in ASP.NET Core

.Making Wrapped Elements in Blazor Easier.
[%collapsible]
====

When we want to wrap and element inside a 'div' element, we can use kbd:[Alt + Shift + W] to instantly wrap the selected tag with a new tag (default div). this works for any level of nesting.

====

=== Debugging Lists in Visual Studio - viewing, sorting, and exporting

.Easier Way to Debug Lists.
[%collapsible]
====

when we look at the debugger at a list, we see the type, and we only see the values when hovering. but if we click the kvd:[view] option, we get a window with a visualizer, which we can sort and filter, and even export.

we can also use records (unchanging data), which has the `toString` default-created and also show the equality contract.
====

=== Using http Files in Visual Studio to Test and Document APIs

.Http Files Define a Series of API Calls
[%collapsible]
====

having an ".http" file that tests and documents apis (including external ones). we can have pages that automatically run calls on the api with our predetermined values.

[source, http]
----
@rootUrl=https://localhost:7197

GET {{rootUrl}}/People

### 

POST {{rootUrl}}/People
content-Type: application/json
{
  "id": 4,
  "firstName": "jane",
  "lastName": "Jones"
}

### 

PUT {{rootUrl}}/People/4
content-Type: application/json
{
  "id": 4,
  "firstName": "Jane",
  "lastName": "Smith"
}

###

DELETE {{rooUrl}}/people/4

###
----

it can work as a mix between documentation and testing, like having a test plan you can execute from code.

====

=== Sticky Scroll is Back! Colorized Braces Are Also Now Available!

.Visual Studio Code Navigation Tips.
[%collapsible]
====

features that return to Visual studio to make navigation easier.

. sticky scroll: still in preview mode (17.6 version), grouping the current scope, freezing the top level statements that our code is nested in.
. colorized braces - different colors for pairs of braces. keep track of which brace goes with which.
====

=== Dev Tunnels Visual Studio in 10 Minutes or Less

.Directing Traffic to Local Machine With A Public Address.
[%collapsible]
====
allowing others to access applications without publishing them. even if they are running on local host.

when running the application, we can create a dev tunnel that will direct traffic to local machine. this is done via the microsoft account, either allowing everybody or just people in the organization to access it. we can use a temporary tunnel (changes when visual studio restarts) or permanent one (reuses the same address). +
when we launch our app, we get a microsoft message informing us it's running a dev tunnel. the address will now be a public address, and we can share it with other people.

====

=== New File Dialog Tips and Tricks for Visual Studio in 10 Minutes or Less

.New Intelligent File Template Creations.
[%collapsible]
====

right clicking and selecting "add new item" (or kbd:[Ctrl + Shift + A]), we get the new dialog.
it knows the naming convention (like cs file, interfaces) and can create the proper template.
we can always use the older look and see all templates. +
we can create multiple files by separating them with commas, or create a folder by passing the path.

====

=== How To Return a Record ID from SQL to C# on Insert

.Working The Stored Procedures for SQL.
[%collapsible]
====

working with SQL tables. we have a stored procedure with an output parameter. this is not the same as the return value (which should be the status code).

[source, sql]
----
CREATE PROCEDURE [dbo].[spPeople_Insert]
  @id int output,
  @firstName nvarchar(50)
AS
begin
  INSERT into People (firstName)
  values (@firstName);

  set @id = SCOPE_IDENTITY();

  return 1; 
end
----

working with Dapper and the new "microsoft.Data.SqlClient" package. we use `DynamicParameters` to connect our code with the stored procedure, we create parameters and their types and execute the procedure. and because we set the value in our procedure, we can use it in the application code.
====

=== Fluent Assertions in Unit Testing in C#

.Making Unit Tests Assertions Easier to Read.
[%collapsible]
====

A 3rd party library from nuget that makes writing assertions together to comprehend.

[source, sharp]
----
[Theory]
[InlineData("Eddie", "Van Haley", "Eddie Van Haley")]
public void TestEdgeCaseNames(string firstName, string lastName, string fullName)
{
  // arrange
  SampleClass sampleClass = new SampleClass(fullName);

  // fluent assertion
  sampleClass.LastName.Should().Be(lastName);

  // multiple assertions
  sampleClass.LastName.Should()
    .StartWith(lastName.Substring(0,3))
    .And.EndWith(lastName.Substring(lastName.Length - 3))
    .And.Contain(" ");
}
----

we can also combine this with the `AssertionScope` to get all the errors from the test (not just the first error).

====

=== Dependency Injection in Minimal APIs in C#

.Dependency Injection Into Minimal APIs
[%collapsible]
====

dependency injection, route parameters, 


we start with a simple case:
[source, csharp]
----
var app = WebApplication.CreateBuilder(args).Build();
app.UseHttpsRedirection();

app.MapGet("/person/{id:int}", (int id) =>
{
  return new PersonRecord(id, "Tim", "Corey");
});

app.MapPost("/person", (PersonRecord person) =>
{
  return person;
});

app.Run();

record PersonRecord(int Id, string FirstName, string LastName);
----

next we add dependency injection and use the configuration file (the appsettings file), each method gets the dependency injection, rather the entire class.

[source, csharp]
----

app.MapGet("/person/{id:int}", (int id, IConfiguration config) =>
{
  return new PersonRecord(id,
  config.GetValue<string>("TestInfo:FirstName"),
  config.GetValue<string>("TestInfo:LastName"));
});

app.MapPost("/person", (PersonRecord person, IConfiguration config) =>
{
  int id = config.GetValue<int>("TestInfo:Id");
  var newPerson = person with {Id = id}; // records are immutable
  return newPerson;
});
----
====

=== 4 Things I Like in The New Visual Studio 2022 17.7 Update

.Changes to Visual Studio
[%collapsible]
====

The file comparison is now built-in into the IDE, allowing to compare any two files, even if they don't belong to the same project. +
Copying text from a file removes the outmost indentations, so the pasted code starts at the start of the line. +
Github Actions have a `create workflow` wizard. +
When viewing file trees, there is now a **Collapse All Descendants** option.

====

=== How to Fix the Inconsistent Accessibility Error in C#

.Returning an Object That Can't Be Used By The Caller
[%collapsible]
====
an error that a "return type '(sometime)' is less accessible than (calling function)" happens when the object returned from a function is less accessible than that of the function that returns it. like returning a class marked "internal" from a public function. this means that someone can call a method and won't be able to use the object they got back. +
there is no problem with retuning a more accessible object.
====

=== The Dictionary Data Structure in C# in 10 Minutes or Less

.Key Value Data Structure
[%collapsible]
====

a key value pair data structure with unique keys. has quick lookup based on keys. really good for lookups.
[source, csharp]
----
Dictionary<int, string> rookieOfTheYear = new();
rookieOfTheYear.Add(2000, "Mike Miller");
rookieOfTheYear.Add(2001, "Jane Doe");
rookieOfTheYear.Add(2002, "Jane Doe"); // legal, repeating value
rookieOfTheYear.Add(2003, "John Smith");
// rookieOfTheYear.Add(2003, "jane Doe"); // illegal, repeating key

if (rookieOfTheYear.Contains(2002)) {
  Console.WriteLine(rookieOfTheYear[2002]);
}
----

====
=== Understanding SQL Auto-Incrementing Identity in 10 Minutes or Less

.Setting An Identity Column To Be Auto-Incrementing
[%collapsible]
====
setting a SQL column to be auto-incrementing and always have a value, we can set a first value (seed) and change the increment. the values are stored in disk in the identity order.

[source, sql]
----
CREATE TABLE [dbo].[DemoPeople]
(
  [Id] INT NOT NULL PRIMARY KEY IDENTITY,
  [FirstName] NVARCHAR(50) NULL,
  [LastName] NVARCHAR(50) NULL
)
----

====
=== Data Annotation Updates in .NET 8

.New Data Annotations To Validate Fields
[%collapsible]
====

.annotations:
* `Length` - required length of a string property
* `Range` - minimal and maximal value of ranges, with the ability to exclude the top or bottom values.
* `AllowedValues` - limit values to specific cases
* `Denied` - disallow specific values

[source, csharp]
----
using System.ComponentsModel.DataAnnotations
namespace DataAnnotationsDemo;
public class EmployeeModel
{
  [Length(5,25)]
  public string? FirstName { get; set; }

  [Range(1,5, MinimumIsExclusive=true, MaximumIsExclusive)]
  public int EvaluationScore { get; set; }

  [AllowedValues("Monday", "Tuesday", "Wednesday","Thursday", "Friday")]
  public string? FavoriteWorkday { get; set; }

  [DeniedValues("None","NA")]
  public string? FavoriteBoss { get; set; }
}
----
====

=== Dependency Injection Updates in .NET - Keyed Implementations

.More Than One Implementation of An Interface Identifiable With a Key.
[%collapsible]
====

we can define more than one interface in dependency injection and request which interface we want based on a key.

Blazor Example:

[source, csharp]
----

public Interface IInteractionMessages{
  string greetings();
}

public class FormalMessages : IInteractionMessages
{
  public string greetings()
  {
    return "FORAML MESSAGE";
  }
}

public class InformalMessages : IInteractionMessages
{
  public string greetings()
  {
    return "message that is, like, chilled";
  }
}

// some more code
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorComponents().
  AddInteractiveServerComponents();
builder.Services.AddKeyedSingleton<IInteractionMessages, FormalMessages>("formal");
builder.Services.AddKeyedSingleton<IInteractionMessages, InformalMessages>("relaxed");
var app = builder.Build();

// usage
public class Demo {
  public Demo([FromKeyedServices("relaxed")] IInteractionMessages messages);
}
----
obviously, the key should probably be an enum. there is some special consideration for blazor code-behind components.
====

=== .NET 8 Adds Shuffle to Random for Arrays and Spans

.Randomly Shuffle Arrays and Spans (in place)
[%collapsible]
====

a new method inside the `Random` class that allows for in-place shuffling of arrays and spans. doesn't support List for now.
[source, csharp]
----
record PersonRecord(string a, string b);

PersonRecord[] people = [
  new("a","b"),
  new("c","d"),
  new("e","f"),
  new("g","h"),
  new("i","j")
];

foreach (var p in people)
{
  Console.WriteLine($"{p.a} {p.b}")
}

Random.Shared.Shuffle(people);
foreach (var p in people)
{
  Console.WriteLine($"{p.a} {p.b}")
}
----

====

=== Collection Expressions in .NET 8

.New expression to initialize collection using the `[]` syntax.
[%collapsible]
====
different ways to initialize collections, and since .NET 8 we can use `[]` to initialize all sorts of collections. it also helps to create empty collections.

[source, csharp]
----
int[] agesArray = {1,2,3};
list<int> agesList = new(){1,2,3};
int[] agesArray2 = [1,2,3];
list<int> agesList2 = [1,2,3];

void PrintAges(IEnumerable<int> ages);
----

this is the same syntax used in pattern matching expressions to match an empty collection.
====

=== Periodic Timer in C# Including .NET 8 Updates

.Run Tasks on a Timer
[%collapsible]
====
the `PeriodicTimer` is single timer class that runs tasks asynchronously. it usually runs in the background (a different thread). it takes a TimeSpan as the argument to the constructor.

this example works in .NET 6 and above. but with .NET 8, we can also change to time period after we created it. and we can turn it off indefinably by changing the period to `TimeOut.InfiniteTimeSpan` (the next tick won't arrive, until we turn it back on). each time it is called, all the ticks are consumed, they don't stack together. 

[source, csharp]
----
using PeriodicTimer timer = new(TimeSpan.fromMilliseconds(1000));
var i = 0;
while (await timer.WaitForNextTickAsync() && i < 5)
{
  Console.WriteLine($"Execution #{i+1} ran at: {DateTime.Now.ToString("hh:mm:ss fff")}");
  i++;
  timer.Period = TimeSpan.fromMilliseconds(1000 * i); // .NET 8
  timer.Period = TimeOut.InfiniteTimeSpan; // .NET 8
}
----
====

=== Command Line Arguments in C# Applications in 10 Minutes or Less
.Using The Command Line Arguments
[%collapsible]
====

The command line arguments are hidden from us when we use top-level statements (we have the implicit `public static void main(String []args)`). but we can always access the arguments via the `args` variable.

[source, csharp]
----
foreach (var arg in args)
{
  Console.WriteLine(arg);
}
----
we need custom logic to match and make sense out of the arguments, but we can always get them.

====

=== CSS Isolation in Blazor Applications in 10 Minutes or Less

.Apply custom style to only a specific component in Blazor
[%collapsible]
====
we create a file with the same name as our razor file, but with the extended ".css" extension, this makes the style apply on to the file with the same name.
if our component file is "demo.razor", our isolated css file name is "demo.razor.css". +
under the hood is uses the css `[attribute]` selector and setting the target identifier.

====

=== How To Use Variables in CSS without SASS or LESS in 10 Minutes or Less

.Using variables natively in CSS
[%collapsible]
====

in the past, we had to write the css value directly, so there was a need to apply another level of abstraction over it, such as SASS, to keep the styles consistent and avoid manual mistakes. the eventual css file would have the values hard coded.
[source, css]
----
h1 {
  background-color: #007bff;
}

h2 {
  color: #007bff;
}
----
however, today we can use variables in native css. this reduces the need for css managers, and makes the styles easier to understand.+
we can define them at any level (such as root), and they must begin with two dashes. we then use them with `var(--var-name)`

[source, css]
----
:root {
  --brand-main: #007bff;
}

h1 {
  background-color: var(--brand-main);
}

h2 {
  color: var(--brand-main);
}
----
====
=== How IDisposable and Using Statements Work Together in C#

.Ensuring Proper resource managements
[%collapsible]
====
C# and the garbage collector handle some resources, but there are other resources which we need to manage as part of the code (files, connections, graphics, other handles...). the `IDisposable` pattern encapsulates managing the resources as part of the code-flow. when the garbage collector handles the memory allocation, it will also run the custom resource disposal code.

the interface has the `public void Dispose()` method, we call on it when we instantiate the object with the `using` statement (not to be confused with the `using` directive). the object will be disposed when we go out of scope.

====

=== Renaming in Visual Studio Using AI
.Context Aware renaming tool 
[%collapsible]
====
part of the github co-pilot tool - "rename suggestions". the AI will suggest names based on the field and the general context.
====

=== Visual Studio Update: Automatically Close Brackets and Quotes

.Surrounding text with brackets
[%collapsible]
====
change to visual studio 2022 (17.9). we can enable it in the tools->options->text editor: display-"automatically surround selections when typing quotes or brackets".

we can select a block of code or text, and then press the open parentheses key and the entire thing is surrounded with it.
====

=== Containerize Your C# Application Easily with the .NET CLI
.Putting the C# code into a container
[%collapsible]
====
easy way to create a docker container without a docker file.

we can simply write the command and the image is created. we can then run it from our docker program. 
[source, shell]
----
dotnet publish --os linux --arch x64 -p:PublishProfile=DefaultContainer -c Release
----

inside our project file, we can set the base image to use something else rather the default.
====

=== Fixing a Common WinForms Bug (CS0103) in 10 Minutes or Less
.Fix for a common bug
[%collapsible]
====

an error that happens when we have an event but we deleted the event code. the event appears in the generated code, but it was removed. when we double-click the object in the designer, it creates code in two files, one of them is hidden from us.

we can delete it from the generated code, or look the object properties in the side bar and remove it from the "events" property.
====

=== Create a GitHub Repo From Existing Code in Visual Studio in 10 Minutes or Less

.Built-in github tools from visual studio
[%collapsible]
====
we can click "create git repository" from the "git changes" windows, and then have a form with good defaults to use, and we can directly push it onto github or azure-devops registry.

====

=== 3 WinForms Setup Tasks You Should Do Right Away in 10 Minutes or Less

.Best Practices with WinForms
[%collapsible]
====

.First Things to change
. Changing the default form name. don't forget to change to form display title.
. Change the default font size in the form - which will be inherited by all elements (if they haven't specified it specifically themselves).
. Set a folder structure and adjust the namespaces

====
== Misc

.Stuff Worth Keeping
[%collapsible%open]
====

[source, csharp]
----
//sample csharp code block
----

====